name: build-rust-binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: run-release-please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
          path: crossover-fixer

  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v6

      - name: install-mingw-toolchain
        run: sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64

      - name: add-windows-target
        run: rustup target add x86_64-pc-windows-gnu

      - name: build-binary
        run: |
          cd crossover-fixer
          cargo build --release --target x86_64-pc-windows-gnu

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: crossover-fixer
          path: crossover-fixer/target/x86_64-pc-windows-gnu/release/crossover-fixer.exe

